// A standalone NodeJS script to parse the CSV and push to MongoDB.
// Run via: node scripts/importGoodreads.js
import fs from 'fs';
import path from 'path';
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load env variables manually since we are running outside Next.js process
dotenv.config({ path: path.join(__dirname, '../.env.local') });

// Schema definitions directly linked
import GoodreadsBook from '../models/GoodreadsBook.js';
import Review from '../models/Review.js';

// Super simple CSV parser logic assuming standard quoting
function parseCSVRow(row) {
    const result = [];
    let cur = '';
    let inQuotes = false;
    for (let i = 0; i < row.length; i++) {
        if (row[i] === '"') {
            inQuotes = !inQuotes;
        } else if (row[i] === ',' && !inQuotes) {
            result.push(cur);
            cur = '';
        } else {
            cur += row[i];
        }
    }
    result.push(cur);
    return result;
}

async function syncData() {
    try {
        console.log('Connecting to MongoDB...', process.env.MONGODB_URI);
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected!');

        const csvPath = path.join(__dirname, '../goodreads_library_export-2.csv');
        console.log('Reading CSV from:', csvPath);

        const data = fs.readFileSync(csvPath, 'utf8');
        const rows = data.split('\n').filter(r => r.trim() !== '');

        const headers = parseCSVRow(rows[0]);
        let ingested = 0;
        let draftsCreated = 0;

        // Clear previous runs
        await GoodreadsBook.deleteMany({});

        for (let i = 1; i < rows.length; i++) {
            const cols = parseCSVRow(rows[i]);
            if (cols.length < headers.length) continue;

            // Assuming standard Goodreads Export headers
            // Book Id, Title, Author, ... My Rating, ... Number of Pages, ... Date Read, Date Added, Bookshelves ...
            const bookId = cols[0];
            const title = cols[1];
            const author = cols[2];
            const myRating = parseInt(cols[7]) || 0;
            const pages = parseInt(cols[10]) || 0;
            const yearPublished = parseInt(cols[11]) || 0;
            const originalPub = parseInt(cols[12]) || 0;

            const dateRead = cols[13] ? new Date(cols[13].replace(/\//g, '-')) : null;
            const dateAdded = cols[14] ? new Date(cols[14].replace(/\//g, '-')) : new Date();
            const bookshelves = cols[15] || '';
            const exclusiveShelf = cols[17] || '';
            const myReview = cols[18] || '';

            const gBook = new GoodreadsBook({
                bookId, title, author, myRating,
                numberOfPages: pages, yearPublished, originalPublicationYear: originalPub,
                dateRead, dateAdded, bookshelves, exclusiveShelf, myReview
            });

            await gBook.save();
            ingested++;

            // Create a draft Review if it's marked as read and the user rated it
            if ((bookshelves.includes('read') || exclusiveShelf.includes('read')) && myRating > 0) {
                // Check if we already have a review for this book
                const existingReview = await Review.findOne({ title });
                if (!existingReview) {
                    await Review.create({
                        title: title,
                        bookAuthor: author,
                        rating: myRating,
                        isDraft: true, // Crucial: Set as draft!
                        description: 'Autogenerated draft from Goodreads Sync',
                        content: myReview || `Draft generated for ${title}. Rating: ${myRating}/5`,
                        genreTags: ['Goodreads Import'],
                        stats: { plot: 5, writing: 5, recommendability: 5, sensitiveScale: 5 }
                    });
                    draftsCreated++;
                }
            }
        }

        console.log(`Successfully ingested ${ingested} Goodreads records.`);
        console.log(`Created ${draftsCreated} Review Drafts!`);
        process.exit(0);
    } catch (err) {
        console.error('Failed!', err);
        process.exit(1);
    }
}

syncData();
